# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/brightrf/public_html/
#     - rsync -av --exclude='.git' ./ $DEPLOYPATH/

---
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/brightrf/public_html/
    - rsync -a --exclude='.git' ./ $DEPLOYPATH/
